.github/scripts/set-repo-secrets.sh
.github/scripts/set-repo-variables.sh
.github/workflows/azure-deploy-streamx.yaml
.github/workflows/azure-undeploy-streamx.yaml
.gitignore
README.md
config/application.properties
mesh/mesh-light.yaml
mesh/mesh.yaml
scripts/env/cloud/append-envs.sh
scripts/env/cloud/destroy-env.sh
scripts/env/cloud/read-infra-env.sh
scripts/env/cloud/setup-env.sh
scripts/ingestion/read-env.sh
spec/model/README.md
spec/model/SxModel.json
terraform/azure/platform/main.tf
terraform/azure/platform/variables.tf

Takeing latest changes from streamx main repo

---

README.md
scripts/publish-all.sh

Mereging latest from streamx repo

---

data/pages/layouts/contentPage.html

Update header links

---

data/templates/pdp.html
data/templates/products-listing-tiles.html

Fix for image and text

---

data/web-resources/js/autocomplete-init.js

- [ x] Non-breaking change
* ... .
* ... .
- [ x] My code follows the [code standards](https://github.com/streamx-dev/streamx/blob/main/CONTRIBUTING.md) of this project
- [ x] Changed code is covered with unit tests
- [ x] I have updated READMEs and java docs (if applicable)

RM: Adding search result class

---

data/templates/pcp.html
data/templates/pdp.html
scripts/publish-code.sh
scripts/publish-products.sh

RM:Adding category to page data-attributes for tracking

---

data/templates/pcp.html

updated nav

---

data/web-resources/js/autocomplete-init.js

JG :: update lumax categories

---

data/pages/fragments/headContent.html
data/templates/pdp.html
data/templates/products-listing-tiles.html

RM: Adding Updates to DL, Target anti-flicker

---

data/templates/pcp.html
data/templates/products-listing-tiles.html
data/web-resources/js/pcp-init.js

- [ x] Non-breaking change
- [x ] Bug fix / minor change
* ... .
* ... .

RM: Adding add-to-cart tracking on PCPs

---

data/templates/products-listing-tiles.html

RM: Updating P to Div

---

data/contexts/pdp-rendering-context
data/templates/pdp.html

RM: Updating twig to html, re-adding feature logic

---

data/templates/pdp.html

RM: Fixing variants logic

---

data/web-resources/js/autocomplete-init.js

RM: Adding search click events to acdl impl

---

data/templates/pdp.twig

Updated product detail page

---

data/web-resources/js/productUtilities.js

Update featured product CTA

---

data/templates/pcp.html

Update pcp scripts

---

data/pages/compositions/homepage.html

update featured products list

---

data/pages/fragments/footLibs.html
data/templates/pcp.html
data/templates/pdp.twig
data/web-resources/js/pcp-init.js
data/web-resources/js/pdp-init.js
data/web-resources/js/productUtilities.js

Add type module

---

data/templates/pdp.twig
data/templates/products-listing-tiles.html
data/web-resources/js/pcp-init.js

JG :: add the DM trcking class for view Details cta

---

data/pages/compositions/my-orders.html
gateway/routes/streamx-web-route.yaml

RM: Adding skeleton orders page

---

data/web-resources/js/autocomplete-init.js

Fixing search result click tracking

---

data/templates/pdp.twig

RM: Fixing missed quote

---

data/templates/pdp.twig
data/web-resources/js/autocomplete-init.js

RM: Updates to JSON structure, search counts

---

data/templates/products-listing-tiles.html

RM: Adding fix for product description to listing-tiles

---

data/templates/pdp.twig

RM:Switchign from literal to string

---

data/pages/compositions/cart.html
data/templates/pcp.html
data/web-resources/js/checkout-form.js
data/web-resources/js/headerUtilities.js

Guest email and checkout mutations

---

data/web-resources/js/add-increase-decrease-quantity-action.js
data/web-resources/js/checkout-form.js
data/web-resources/js/decorators/decorate-cart.js
data/web-resources/js/graphQLMutations/cartMutations.js
data/web-resources/js/graphQLMutations/checkoutMutations.js
data/web-resources/js/graphQLMutations/userMutations.js
data/web-resources/js/graphQLMutations/utility.js
data/web-resources/js/headerUtilities.js
data/web-resources/js/pdp-init.js
data/web-resources/js/productUtilities.js

JG :: convert LS to SS

---

data/pages/fragments/footLibs.html
data/web-resources/js/analytics-functions.js

RM: Moving launch custom js into app

---

data/pages/fragments/footLibs.html
data/web-resources/js/analytics-functions.js
data/web-resources/js/pcp-init.js
data/web-resources/js/pdp-init.js
data/web-resources/js/productUtilities.js

RM: Updating analytics-functions to module

---

data/web-resources/js/productUtilities.js

RM: Forgot an event

---

data/web-resources/js/checkout-form.js
data/web-resources/js/load-orders.js

Fix checkout form issue

---

data/pages/compositions/cart.html
data/web-resources/js/checkout-form.js
data/web-resources/js/decorators/decorate-cart.js
data/web-resources/js/headerUtilities.js
data/web-resources/js/productUtilities.js

Fix login on checkout page

---

data/web-resources/js/analytics-functions.js
data/web-resources/js/checkout-form.js

RM:Adding purchase event

---

data/pages/compositions/login.html
data/web-resources/js/login-form.js

RM: UI polish

---

data/pages/compositions/cart.html
data/web-resources/js/checkout-form.js
data/web-resources/js/decorators/decorate-cart.js

Update payment UI

---

data/web-resources/js/edsComponentInit.js
data/web-resources/js/graphQLMutations/userMutations.js
data/web-resources/js/login-form.js
data/web-resources/js/user-session-utils.js

RM: EDS Testing Updates

---

data/web-resources/js/graphQLMutations/userMutations.js
data/web-resources/js/login-form.js

Login updates

---

data/pages/compositions/login.html
data/web-resources/js/login-form.js

RM: moving quicklinks

---

data/pages/fragments/headContent.html
data/pages/layouts/contentPage.html

RM: Moving meta-tag for host

---

data/web-resources/js/login-form.js

RM: removing logs

---

data/pages/fragments/footLibs.html

RM: Removing old ref

---

data/templates/pdp.twig

JG :: add XF include on pdp

---

data/web-resources/js/pcp-init.js

<DO NOT MERGE> JG :: disable load more on pcp

---

data/web-resources/js/checkout-form.js

RM: Fixing cart clear on successful purchase.

---

mesh/deployment.yaml
mesh/mesh.yaml
terraform/azure/platform/main.tf

* [DXP-2166] Stateful delivery services mesh and deployment configs
* bump operator version to 0.0.17
---------
* ... .
* ... .

[DXP-2166] Stateful delivery services mesh and deployment configs (#101)

---

mesh/deployment.yaml
mesh/mesh.yaml
terraform/azure/platform/main.tf

Reverting changes from 8/25 morning merge due to stability issue.

Revert "[DXP-2166] Stateful delivery services mesh and deployment configs (#101)"
